### ISSUE TITLE
Failed to load CoreNFC on ios crash.

### ISSUE THREAD

**Issue by sgehrman** [okadan/flutter-nfc-manager#16]
dyld: Library not loaded: /System/Library/Frameworks/CoreNFC.framework/CoreNFC
  Referenced from: /var/containers/Bundle/Application/EB1AFB0C-E3D8-4400-ACED-58AB61EA86F9/Runner.app/Runner
  Reason: image not found

I noticed nfc_in_flutter has this in their podspec, I tried this, but it didn't help.
  s.weak_frameworks = ['CoreNFC']

Possible fix:  https://stackoverflow.com/questions/44946057/dyld-library-not-loaded-rpath-corenfc-framework-corenfc-ios11-and-xcode-9-be

or see: https://github.com/semlette/nfc_in_flutter/issues/20

I just updated Xcode, not sure if this was the cause, but it just started happening.

I'm testing on an iPhone 6.

I tried a bunch of stuff online.  Nothing worked.  But I found this: https://medium.com/5-minute-break-while-coding/create-a-mostly-swift-framework-with-optional-features-7e8a9ac960f9

**Comment by AirborneEagle** [comment]
Are you saying you were able to get it working on the iPhone 6, but it has since stopped working?
From what I can tell, NFC reads were not allowed by third party applications on anything prior to the iPhone 7.
https://www.bluebite.com/nfc/iphone-nfc-compatibility
I have a 6s, and I am finding that `await NfcManager.instance.isAvailable()` returns `false`
and if I try to read a card anyways, nothing happens. 

pubspec: ` nfc_manager: ^1.3.2+4`

**Comment by andreasmpet** [comment]
I can confirm that using this project will make an app unable to run on iPhone 6.

Adding the [line specified here,](https://github.com/semlette/nfc_in_flutter/pull/28/commits/3041739cff32ade8659517f0c732496778652500) fixes the problem. I've created a PR (#65) about this.

**Comment by ThirupathiRaoM** [comment]
Hello Every one 
I am Working coreNFC Project I can Able read and write the NFC Tag I am Getting issue while password protected the NFC device using CoreNFC if any body having the idea regarding please let us know it will help me a lot 
Thanks & Regards
iOS Developer
