### ISSUE TITLE
NFC functionality suddenly stopped working with iso7816, throwing PlatformException

### ISSUE THREAD

**Issue by khaled-ET** [okadan/flutter-nfc-manager#184]
For over 8 months, the NFC functionality with iso7816 has been operating smoothly. However, it has abruptly ceased to function. Upon testing, an error message is encountered when attempting to send commands to the card. The error message reads as follows:

**PlatformException(2, Missing required entitlement, null, null)**

NOTE: This issue affects iOS devices only.

**Comment by khaled-ET** [comment]
It appears that iOS restricts the selection of another Applet ID (AID) if it's not listed in the info.plist file. After configuring the info.plist file to include the necessary AID and entitlements related to NFC and ISO7816, the problem was resolved. NFC functionality is now operating smoothly on iOS devices.

**Comment by ced1check** [comment]
I've published my app on App Store, so I suspect I have a valid AID, how do I check if info.plist contains appropriate definition  so that NFC starts working?
I'm getting Missing required entitlement at this time. Thanks.

Found a solution here: https://github.com/okadan/flutter-nfc-manager/issues/91#issuecomment-1319897175
